# Write your MySQL query statement below
select DATE_FORMAT(TRANS_DATE, "%Y-%m") as MONTH,
COUNTRY,
Count(ID) as TRANS_COUNT,
SUM(IF(STATE = 'approved', 1, 0)) as APPROVED_COUNT,
SUM(AMOUNT) as TRANS_TOTAL_AMOUNT,
SUM(IF(STATE = 'approved', AMOUNT, 0)) as APPROVED_TOTAL_AMOUNT
from TRANSACTIONS
group by  COUNTRY, MONTH


-- # Write your MySQL query statement below
-- SELECT DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH, COUNTRY, COUNT(ID) AS TRANS_COUNT,
-- SUM(IF(STATE = 'approved', 1, 0)) AS APPROVED_COUNT, SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
-- SUM(IF(STATE = 'approved', AMOUNT, 0)) AS APPROVED_TOTAL_AMOUNT FROM TRANSACTIONS
-- GROUP BY COUNTRY, MONTH;